name: Alerta CI/CD Test

on:
  push:
    branches:
      - master

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test self-hosted runner
        run: |
          echo "GitHub Actions is running on my Ubuntu machine"
          echo "Hostname:"
          hostname
          echo "User:"
          whoami
          echo "Current directory:"
          pwd

      - name: Test environment
        run: |
          echo "Ubuntu:"
          cat /etc/os-release
          echo "Python:"
          python3 --version || true
